name: random_task_provider
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  provider: ^6.1.5
  intl_phone_field: ^3.2.0
  flutter_svg: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svg/

  fonts:
    - family: Lora
      fonts:
        - asset: assets/font/Lora-SemiBold.ttf
          weight: 500
    - family: Raleway
      fonts:
        - asset: assets/font/Raleway-Medium.ttf
        - asset: assets/font/Raleway-SemiBold.ttf